[package]
name = "release-maker"
version = "0.1.0"
authors = ["Alex M. M. <acdenissk69@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1"
structopt = "0.3"
rmaker = { path = "librmaker" }
